name: conda-env
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.13
  - ampl-asl=1.0.0
  - anyio=4.7.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - attrs=24.3.0
  - aws-c-auth=0.8.0
  - aws-c-cal=0.8.1
  - aws-c-common=0.10.6
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.2
  - aws-c-io=0.15.3
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.7
  - aws-c-sdkutils=0.2.1
  - aws-checksums=0.2.2
  - aws-crt-cpp=0.29.7
  - aws-sdk-cpp=1.11.458
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - babel=2.16.0
  - beautifulsoup4=4.12.3
  - bleach=6.2.0
  - blosc=1.21.6
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - c-blosc2=2.15.2
  - ca-certificates=2024.12.14
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.2
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - cloudpickle=3.1.0
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.1
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - dbus=1.13.6
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - double-conversion=3.3.0
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.55.3
  - fqdn=1.5.1
  - freetype=2.12.1
  - gflags=2.2.2
  - glog=0.7.1
  - graphite2=1.3.13
  - h11=0.14.0
  - h2=4.1.0
  - h5py=3.12.1
  - harfbuzz=9.0.0
  - hdf5=1.14.4
  - hpack=4.0.0
  - httpcore=1.0.7
  - httpx=0.28.1
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib_resources=6.4.5
  - ipopt=3.14.17
  - ipykernel=6.29.5
  - ipyparallel=9.0.0
  - ipython=8.31.0
  - ipywidgets=8.1.5
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.5
  - json5=0.10.0
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.11.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.3
  - libarrow=18.1.0
  - libarrow-acero=18.1.0
  - libarrow-dataset=18.1.0
  - libarrow-substrait=18.1.0
  - libblas=3.9.0
  - libboost=1.86.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp19.1=19.1.6
  - libclang13=19.1.6
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=8.11.1
  - libdeflate=1.23
  - libdrm=2.4.124
  - libedit=3.1.20191231
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgl=1.7.0
  - libglib=2.82.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libgoogle-cloud=2.32.0
  - libgoogle-cloud-storage=2.32.0
  - libgrpc=1.67.1
  - libhwloc=2.11.2
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm19=19.1.6
  - liblzma=5.6.3
  - liblzma-devel=5.6.3
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libopenblas=0.3.28
  - libopengl=1.7.0
  - libparquet=18.1.0
  - libpciaccess=0.18
  - libpng=1.6.44
  - libpq=17.2
  - libprotobuf=5.28.2
  - libre2-11=2024.07.02
  - libscotch=7.0.4
  - libsodium=1.0.20
  - libspral=2024.05.08
  - libsqlite=3.47.2
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libutf8proc=2.9.0
  - libuuid=2.38.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.7.0
  - libxml2=2.13.5
  - libxslt=1.1.39
  - libzlib=1.3.1
  - loguru=0.7.2
  - lxml=5.3.0
  - lz4-c=1.10.0
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - metis=5.1.0
  - mistune=3.0.2
  - mumps-include=5.7.3
  - mumps-seq=5.7.3
  - munkres=1.1.4
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - nbclient=0.10.2
  - nbconvert-core=7.16.4
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nlopt=2.9.0
  - nomkl=1.0
  - notebook=7.3.2
  - notebook-shim=0.2.4
  - numexpr=2.10.2
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openssl=3.4.0
  - orc=2.0.3
  - overrides=7.7.0
  - packaging=24.2
  - pagmo=2.19.1
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pip=24.3.1
  - pixman=0.44.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.48
  - prompt_toolkit=3.0.48
  - psutil=6.1.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py-cpuinfo=9.0.0
  - pyarrow=18.1.0
  - pyarrow-core=18.1.0
  - pybind11-abi=4
  - pycparser=2.22
  - pygments=2.18.0
  - pygmo=2.19.7
  - pyparsing=3.2.0
  - pyside6=6.8.1
  - pysocks=1.7.1
  - pytables=3.10.2
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python-tzdata=2024.2
  - python_abi=3.11
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - qt6-main=6.8.1
  - re2=2024.07.02
  - readline=8.2
  - referencing=0.35.1
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.22.3
  - s2n=1.5.10
  - send2trash=1.8.3
  - setuptools=75.6.0
  - six=1.17.0
  - snappy=1.2.1
  - sniffio=1.3.1
  - soupsieve=2.5
  - stack_data=0.6.3
  - tbb=2022.0.0
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.2.1
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20241206
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2024b
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - urllib3=2.3.0
  - wayland=1.23.1
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.43
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.10
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xz=5.6.3
  - xz-gpl-tools=5.6.3
  - xz-tools=5.6.3
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zlib-ng=2.2.3
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - annotated-types==0.7.0
      - cairocffi==1.7.1
      - cairosvg==2.7.1
      - cssselect2==0.7.0
      - cython==3.0.11
      - gpy==1.13.2
      - hjson==3.1.0
      - iapws==1.5.4
      - kaleido==0.2.1
      - med-model-r2023b==23.2
      - numpy==1.26.4
      - optimparallel==0.1.3
      - paramz==0.9.6
      - phd-visualizations==0.1.0
      - plotly==5.24.1
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - scipy==1.12.0
      - seaborn==0.13.2
      - simple-pid==2.0.1
      - solarmed-modeling==0.3.0
      - solarmed-optimization==0.1.0
      - tenacity==9.0.0
      - transitions==0.9.2
prefix: /app/miniconda3/envs/conda-env
